# fly.toml app configuration file generated for pay-cosern on 2024-03-01T04:54:05-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pay-cosern'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  DATABASE_PATH="mnt/paycosern/paycosern.db"

[mounts]
  source="paycosern"
  destination="/mnt/paycosern"
